redundancy = 2
core_ann_interval = 10
beacon_interval = 5
cache_size = 5000

[host]
id = 4
uri = "tcp://localhost:1884"

[[neighbors]]
id = 1
uri = "tcp://localhost:1881"

[[neighbors]]
id = 5
uri = "tcp://localhost:1885"

[[neighbors]]
id = 7
uri = "tcp://localhost:1887"
