redundancy = 2
core_ann_interval = 10
beacon_interval = 5
cache_size = 5000

[host]
id = 9
uri = "tcp://localhost:1889"

[[neighbors]]
id = 6
uri = "tcp://localhost:1886"

[[neighbors]]
id = 8
uri = "tcp://localhost:1888"
