redundancy = 2
core_ann_interval = 10
beacon_interval = 5
cache_size = 5000

[host]
id = 5
uri = "tcp://localhost:1885"

[[neighbors]]
id = 2
uri = "tcp://localhost:1882"

[[neighbors]]
id = 4
uri = "tcp://localhost:1884"

[[neighbors]]
id = 6
uri = "tcp://localhost:1886"

[[neighbors]]
id = 8
uri = "tcp://localhost:1888"
